inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - db/schema.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false
